export const siteConfig = {
  name: "Oftisoft",
  title: "Premium Software Development Company | Oftisoft",
  description: "Transform your digital vision into reality with Oftisoft. We build high-performance web applications, mobile apps, AI solutions, and enterprise software. Based in Bangladesh, serving global clients.",
  shortDescription: "Premium software development company specializing in web, mobile, and AI solutions.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://oftisoft.com",
  email: "oftisoft@gmail.com",
  phone: "+8801757220402",
  whatsapp: "+8801757220402",
  address: {
    street: "Sultanpur Sahapara",
    city: "Satkhira",
    region: "Khulna",
    country: "Bangladesh",
    postalCode: "9400",
  },
  coordinates: {
    lat: 22.7183,
    lng: 89.0707,
  },
  founded: 2019,
  founder: "Rasel Hossain",
  social: {
    github: "https://github.com/oftisoft",
    linkedin: "https://linkedin.com/company/oftisoft",
    twitter: "https://twitter.com/oftisoft",
    facebook: "https://facebook.com/oftisoft",
    instagram: "https://instagram.com/oftisoft",
    youtube: "https://youtube.com/oftisoft",
  },
  links: {
    github: "https://github.com/oftisoft",
    linkedin: "https://linkedin.com/company/oftisoft",
    twitter: "https://twitter.com/oftisoft",
    facebook: "https://facebook.com/oftisoft",
    instagram: "https://instagram.com/oftisoft",
    youtube: "https://youtube.com/oftisoft",
  },
  keywords: [
    "software development",
    "web development",
    "mobile app development",
    "AI solutions",
    "SaaS development",
    "enterprise software",
    "custom software",
    "Bangladesh software company",
    "React development",
    "Next.js development",
    "Node.js development",
    "full-stack development",
    "digital transformation",
    "cloud solutions",
    "DevOps services",
  ],
  services: [
    "Web Development",
    "Mobile App Development",
    "AI & Machine Learning",
    "SaaS Development",
    "Enterprise Solutions",
    "Cloud Architecture",
    "DevOps & CI/CD",
    "UI/UX Design",
  ],
  industry: "Software Development",
  priceRange: "$$$",
  openingHours: {
    monday: "09:00-18:00",
    tuesday: "09:00-18:00",
    wednesday: "09:00-18:00",
    thursday: "09:00-18:00",
    friday: "09:00-18:00",
    saturday: "09:00-18:00",
    sunday: "Closed",
  },
  currency: "USD",
  language: "en-US",
  timezone: "Asia/Dhaka",
};
